<?php declare(strict_types=1); require_once __DIR__ . '/auth.php'; $user=require_login(); $ua=$_SERVER['HTTP_USER_AGENT']??''; if (preg_match('/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini|Mobile/i',$ua)) { header('Location: dashmovil.php',true,302); exit; } ?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Conversaciones | Victor</title><link rel="stylesheet" href="style.css"></head><body>
<header class="topbar"><div><p class="eyebrow">LIBERATE DE TUS DEUDAS.CL</p><h1>Conversaciones</h1></div><div class="account"><span>Identificado como: <?= htmlspecialchars($user['username']) ?></span><a href="index.php?logout=1">Salir</a></div></header>
<main class="wa-shell"><aside class="inbox"><div class="inbox-head"><h2>Chats</h2><span id="sync">Sincronizando...</span></div><label class="search"><span>Buscar</span><input id="client-search" placeholder="Nombre o teléfono" autocomplete="off"></label><div id="clients" class="client-list">Cargando...</div></aside>
<section class="chat"><div class="chat-head"><div><p class="eyebrow">CONVERSACIÓN</p><h2 id="selected">Selecciona un cliente</h2></div><span class="bot-status"><i></i> Bot conectado</span></div><textarea id="notes" class="notes" placeholder="Notas internas del cliente"></textarea><div id="conversation" class="conversation"><div class="empty">Selecciona un chat para ver los mensajes.</div></div><?php if (in_array($user['role'] ?? '', ['victor','tester'], true)): ?><form id="reply" class="composer"><textarea required placeholder="Responder como el bot"></textarea><button type="submit">Enviar</button></form><?php endif; ?></section></main>
<script>const csrf=<?=json_encode(csrf_token())?>,clients=document.querySelector('#clients');let current=null,currentClient=null;
function esc(s){return String(s??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[x]));}
async function loadClients(){try{const q=encodeURIComponent(document.querySelector('#client-search').value),r=await fetch('api/clients.php?q='+q),d=await r.json();clients.innerHTML=d.data.map(c=>`<button class="client ${c.phone===current?'selected':''}" data-phone="${esc(c.phone)}"><span class="avatar">${esc((c.name||c.phone).slice(0,1).toUpperCase())}</span><span class="client-copy"><b>${esc(c.name||'Sin nombre')}</b><small>${esc(c.phone)} · ${esc(c.status||'new')}</small></span></button>`).join('')||'<p class="empty">Sin clientes todavía.</p>';clients.querySelectorAll('.client').forEach(b=>b.onclick=()=>openChat(b.dataset.phone,d.data.find(c=>c.phone===b.dataset.phone)));document.querySelector('#sync').textContent='Actualizado ahora';}catch(e){document.querySelector('#sync').textContent='Error de conexión';}}
async function openChat(phone,c){current=phone;currentClient=c;document.querySelector('#selected').textContent=c.name||phone;document.querySelector('#notes').value=c.notes||'';await loadConversation();loadClients();}
async function loadConversation(){if(!current)return;const r=await fetch('api/conversations.php?phone='+encodeURIComponent(current)),d=await r.json(),box=document.querySelector('#conversation');box.innerHTML=d.data.map(m=>`<div class="message ${m.role}"><p>${esc(m.content)}</p><time>${esc(m.created_at||'')}</time></div>`).join('')||'<div class="empty">Sin mensajes todavía.</div>';box.scrollTop=box.scrollHeight;}
async function post(url,payload){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw Error(d.error||'No se pudo completar');return d;}
document.querySelector('#client-search').oninput=loadClients;let notesTimer;document.querySelector('#notes').oninput=()=>{clearTimeout(notesTimer);notesTimer=setTimeout(async()=>{if(!current||!currentClient)return;try{await post('api/update-client.php',{phone:current,status:currentClient.status||'new',notes:document.querySelector('#notes').value});document.querySelector('#sync').textContent='Notas guardadas';}catch(e){document.querySelector('#sync').textContent='No se pudieron guardar las notas';}},700);};
const form=document.querySelector('#reply');if(form)form.onsubmit=async e=>{e.preventDefault();const field=form.querySelector('textarea'),content=field.value.trim();if(!current||!content)return;try{await post('api/reply.php',{phone:current,content});field.value='';await loadConversation();}catch(e){alert(e.message);}};
loadClients();setInterval(async()=>{await loadClients();await loadConversation();},5000);</script></body></html>
